image:
  tag: v0.0.36
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: frontend.dev.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nginx-frontend-tls
      hosts:
        - frontend.dev.veryred.ru

env:
  apiBase: "https://main-backend.dev.veryred.ru/api"
