image:
  tag: v0.0.36
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: englab.dev.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: englab-tls
      hosts:
        - englab.dev.veryred.ru
