image:
  tag: v0.0.36
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: transcriber.dev.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: transcriber-tls
      hosts:
        - transcriber.dev.veryred.ru
