# Values for Vaultwarden deployment
# Только переопределения относительно дефолтных values.yaml

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: vaultwarden.dev.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vaultwarden-tls
      hosts:
        - vaultwarden.dev.veryred.ru

persistence:
  storageClass: longhorn # поменять на longhorn-retain, но его создать сначала надо бы 

env:
  DOMAIN: "https://vaultwarden.dev.veryred.ru"
  # Uncomment and configure as needed:
  # ADMIN_TOKEN: ""
  # SIGNUPS_ALLOWED: "true"
  # INVITATIONS_ALLOWED: "true"
  # WEBSOCKET_ENABLED: "true"

