image:
  tag: v0.0.8
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: main-backend.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: main-backend-tls
      hosts:
        - main-backend.veryred.ru
