image:
  tag: v0.0.7
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: noauth.veryred.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: noauth-transcriber-tls
      hosts:
        - noauth.veryred.ru
